language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nosetests

env:
  global:
    secure: TiX4MSOovChbs5oO61zzVNS+Y7BTYZ2gS33ia5szsVBoxnSqZmbgWbynSd124VEeQZPtfVHoErQv5dnsXSsTCrqM9/lfIAhuXcOw5I0DMVtJiJLOoOztfZeQg1MY3TJrxckSi8V9/3cSvII1sGzIjuTaH0RbHH8Ekzj6D9aJFpA=

before_install:
- openssl aes-256-cbc -K $encrypted_2e78d78dcfa0_key -iv $encrypted_2e78d78dcfa0_iv
  -in deploy_key.pem.enc -out .travis/deploy_key.pem -d

after_success:
- chmod 600 .travis/deploy_key.pem
- ssh-add .travis/deploy_key.pem
- git remote add production PRODUCTION_SERVER
- git push production
