"""empty message

Revision ID: 1723c3826154
Revises: 516db30e0484
Create Date: 2015-02-15 16:51:19.706000

"""

# revision identifiers, used by Alembic.
revision = '1723c3826154'
down_revision = '516db30e0484'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users', 'user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.rename_table('user', 'users')
    ### end Alembic commands ###
