"""empty message

Revision ID: 184a10ff9281
Revises: 516db30e0484
Create Date: 2015-02-11 00:51:21.313000

"""

# revision identifiers, used by Alembic.
revision = '184a10ff9281'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_of_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint('series_of_user.user_id', 'user.id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_of_user')
    ### end Alembic commands ###
