"""empty message

Revision ID: 4daa42ec41d8
Revises: 1723c3826154
Create Date: 2015-02-15 16:58:44.828000

"""

# revision identifiers, used by Alembic.
revision = '4daa42ec41d8'
down_revision = '1723c3826154'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, INTEGER, ForeignKey


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_of_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('series_of_user', Column('user_id', INTEGER, ForeignKey('user.id')))
    op.add_column('series_of_user', Column('series_id', INTEGER))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_of_user')
    ### end Alembic commands ###
